<?xml version="1.0" encoding="utf-8"?>
<TestRecord xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Tests>
    <TestRecord Name="PasswordUsher">
      <Tests>
        <TestRecord Name="Core">
          <Tests>
            <TestRecord Name="Tests">
              <Tests>
                <TestRecord Name="AccountDataAccessTests">
                  <Tests>
                    <TestRecord Name="can_get_by_provider">
                      <Results>
                        <UnitTestResult>
                          <TestDate>2012-05-13T03:26:36</TestDate>
                          <Status>Failure</Status>
                          <TotalFailures>1</TotalFailures>
                          <TotalSuccess>0</TotalSuccess>
                          <TotalIgnored>0</TotalIgnored>
                          <Time />
                          <Message>  Expected: 1
  But was:  0
</Message>
                          <StackTrace>  at NUnit.Framework.Assert.That (System.Object actual, IResolveConstraint expression, System.String message, System.Object[] args) [0x00000] in &lt;filename unknown&gt;:0 
  at NUnit.Framework.Assert.AreEqual (Int32 expected, Int32 actual) [0x00000] in &lt;filename unknown&gt;:0 
  at PasswordUsher.Core.Tests.AccountDataAccessTests.can_get_by_provider () [0x0000f] in /home/chirdeep/Projects/password-usher/PasswordUsher/PasswordUsher.Core.Tests/AccountDataAccessTests.cs:57 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&amp;)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in &lt;filename unknown&gt;:0 </StackTrace>
                          <ConsoleOutput />
                          <ConsoleError>Connecting to: main
</ConsoleError>
                        </UnitTestResult>
                      </Results>
                    </TestRecord>
                    <TestRecord Name="can_get_all_accounts">
                      <Results>
                        <UnitTestResult>
                          <TestDate>2012-05-13T03:26:53</TestDate>
                          <Status>Failure</Status>
                          <TotalFailures>1</TotalFailures>
                          <TotalSuccess>0</TotalSuccess>
                          <TotalIgnored>0</TotalIgnored>
                          <Time />
                          <Message>  Expected: greater than 0
  But was:  0
</Message>
                          <StackTrace>  at NUnit.Framework.Assert.That (System.Object actual, IResolveConstraint expression, System.String message, System.Object[] args) [0x00000] in &lt;filename unknown&gt;:0 
  at NUnit.Framework.Assert.Greater (Int32 arg1, Int32 arg2) [0x00000] in &lt;filename unknown&gt;:0 
  at PasswordUsher.Core.Tests.AccountDataAccessTests.can_get_all_accounts () [0x0000c] in /home/chirdeep/Projects/password-usher/PasswordUsher/PasswordUsher.Core.Tests/AccountDataAccessTests.cs:33 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&amp;)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in &lt;filename unknown&gt;:0 </StackTrace>
                          <ConsoleOutput />
                          <ConsoleError>Connecting to: main
</ConsoleError>
                        </UnitTestResult>
                      </Results>
                    </TestRecord>
                  </Tests>
                </TestRecord>
                <TestRecord Name="ProviderDataAccessTests">
                  <Tests>
                    <TestRecord Name="can_get_all_service_records">
                      <Results>
                        <UnitTestResult>
                          <TestDate>2012-05-13T03:27:08</TestDate>
                          <Status>Success</Status>
                          <TotalFailures>0</TotalFailures>
                          <TotalSuccess>1</TotalSuccess>
                          <TotalIgnored>0</TotalIgnored>
                          <Time />
                          <Message>Test successful

Execution time: 0.15ms</Message>
                          <ConsoleOutput />
                          <ConsoleError>Connecting to: main
</ConsoleError>
                        </UnitTestResult>
                      </Results>
                    </TestRecord>
                  </Tests>
                </TestRecord>
              </Tests>
            </TestRecord>
          </Tests>
        </TestRecord>
      </Tests>
    </TestRecord>
  </Tests>
</TestRecord>